### ISSUE TITLE
Infernal Warbringers sometimes procs infinitely, occasionally server crashing and always killing the player.

### ISSUE THREAD

**Issue by BillytheOrc** [BillytheOrc/ProjectTempest-ISSUETRACKER#1]
I should have a fix for this soon.

**Comment by Levitanious** [comment]
As reported by Doc:

> The Infernal Warbringer in Hellfire Peninsula's Immolation spell has a brokenly high tick rate, so much that I was killed by 2 of them (and some imps that did almost no damage) in about 8 seconds.
![busted immolate](https://user-images.githubusercontent.com/41592877/43246328-eddc2ab0-9076-11e8-8a6c-7e88c11017b5.PNG)

**Comment by BillytheOrc** [comment]
Not yet @Levitanious - Will do it right now.

**Comment by BillytheOrc** [comment]
This fix should be pushed now. If it doesn't work I'm gonna ragequit life.
