### ISSUE TITLE
The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Odiano** [BillytheOrc/ProjectTempest-ISSUETRACKER#16]
![wowscrnshot_071818_215120](https://user-images.githubusercontent.com/41393811/42904499-8ffebe86-8ad5-11e8-81b8-f847f3e9f931.jpg)
During the exorcism quest the orbs keep spawning every 0.5 to 1s making it impossible to kill them all on lower levels without certain aoe abilities. At some point there's like 15-20 of them in a room, and they also during movement go into the ceiling entering the line of sight. After failing the quest they do not disappear, they stay in room till you kill them 1 by 1.

**Comment by BillytheOrc** [comment]
Investigating the script now. Thanks for your report!

**Comment by BillytheOrc** [comment]
Closed thanks to MantisLord @ CMaNGOS team

**Comment by BillytheOrc** [comment]
https://github.com/MantisLord
