### ISSUE TITLE
Mass Dispel not dispelling immunities

### ISSUE THREAD

**Issue by BillytheOrc** [BillytheOrc/ProjectTempest-ISSUETRACKER#26]
Title. High priority.

**Comment by Levitanious** [comment]
We're talking about [this](http://www.wowhead.com/spell=32375/mass-dispel) spell?

**Comment by Levitanious** [comment]
That's where we have our change, iirc: [link](https://github.com/cmangos/mangos-tbc/blob/d1f8fa9d1d39467c7de2bbc602fb13150ee6f3a9/src/game/Spells/SpellEffects.cpp#L5760)

**Comment by Levitanious** [comment]
That's what _should_ be called but somehow doesn't work (Immunity flags?): [link](https://github.com/cmangos/mangos-tbc/blob/8cf68298d77dab521d5bc088f7292009c68fff04/src/game/Entities/Unit.cpp#L4860)

**Comment by Levitanious** [comment]
Apparently it wasn't a bug at all xD
