### ISSUE TITLE
Infernal Warbringer Immolation High Tick Rate

### ISSUE THREAD

**Issue by doctahkill** [BillytheOrc/ProjectTempest-ISSUETRACKER#31]
The Infernal Warbringer in Hellfire Peninsula's Immolation spell has a brokenly high tick rate, so much that I was killed by 2 of them (and some imps that did almost no damage) in about 8 seconds.
![busted immolate](https://user-images.githubusercontent.com/41592877/43246328-eddc2ab0-9076-11e8-8a6c-7e88c11017b5.PNG)

**Comment by Levitanious** [comment]
Related to #1

**Comment by Levitanious** [comment]
@BillytheOrc I imagine you've fixed the crashing, but not the proc rate?

**Comment by Levitanious** [comment]
Closing in favor of root issue.

**Comment by BillytheOrc** [comment]
Doctah, you just can't get a break from all the mobs one-shotting you, can you?
