### ISSUE TITLE
Mennu the Betrayer

### ISSUE THREAD

**Issue by BillytheOrc** [BillytheOrc/ProjectTempest-ISSUETRACKER#34]
He's flat out missing a C++ script. Gonna fix soon.

**Comment by BillytheOrc** [comment]
It's common practice for even lower level and complexity mobs to have C++ scripts, no?

**Comment by AnonXS** [comment]
bosses, yes but in this case and for example [tavaroks](http://www.wowhead.com/npc=18343/tavarok) case its not really needed as they are really straight forward.

What does require cpp scripting for Mennu is his fire totem which currently is disfunctional.

**Comment by BillytheOrc** [comment]
Thanks for your insight. I might write a script for totem and share it with CMaNGOS :D
