### ISSUE TITLE
Rage Refund

### ISSUE THREAD

**Issue by Shulginx** [BillytheOrc/ProjectTempest-ISSUETRACKER#39]
Heroic Strike doesn't refund rage after dodge yet refunds after parry.

Can't speak for other special attacks but i would imagine it would affect all yellow dmg attacks that cost rage.

**Comment by BillytheOrc** [comment]
AFAIK only white attacks are supposed to refund rage on miss/dodge/parry.

**Comment by Shulginx** [comment]
White attacks don't cost rage

**Comment by Shulginx** [comment]
It's a threat breaker for prot warriors and severely fucks Arms in pvp

**Comment by BillytheOrc** [comment]
Yeah, it's something I'm gonna do some research on today before launch.

**Comment by BillytheOrc** [comment]
I believe I have a fix for this. I'll be testing it when the release build goes up.

**Comment by BillytheOrc** [comment]
This issue appears to be solved in the most recent build.
