### ISSUE TITLE
The Violet Tower - Debuff missing

### ISSUE THREAD

**Issue by ATrec** [BillytheOrc/ProjectTempest-ISSUETRACKER#40]
As stated in the title the Violet Tower located in netherstorm is suppose to give you a debuff reducing damage done by 50%

**Comment by BillytheOrc** [comment]
It'd be helpful if you have the spellID for this, but thanks for the bug report. I'll work on fixing it rq.

**Comment by BillytheOrc** [comment]
Fixed!
