### ISSUE TITLE
We need a Plan (TM)

### ISSUE THREAD

**Issue by Levitanious** [BillytheOrc/ProjectTempest-ISSUETRACKER#5]
---
#### First things first:
- [x] What's our development roadmap?
- [x] Do we have an issue-tracker?
> Yup, that we do now :3
- [x] Do we know exactly the costs of running the server on regular basis?

#### What our server going to be at launch?
- [x] XP rates?
- [x] Where the server will be hosted?
- [x] "Premium"-shop is a thing or not?
- [x] The progression thing, where we are starting at?

#### People want stuff, we might consider these?
- Rates: "x5 / x6 across 1-58 lvl, x3 for 58-70 and no %"
- There's continuous call for server in EU /shrug
- People want us to advertise, are we ready? I don't think so.
---

I believe that we're releasing at **July 31st**, so it's a good idea to fill the gaps beforehand.

Meanwhile i'll be watching this issue and updating when more stuff will come up.

**Comment by BillytheOrc** [comment]
Server will certainly be hosted in US.


The progression is going like this: Launch with dungeons & heroics (revered required for heroic keys), Karazhan after the first round of 70s. After that, we have a Blizzlike launch plan but extended timers because of how difficult content is intended to be.

**Comment by Levitanious** [comment]
@BillytheOrc In case you still haven't noticed -- i have a public email in my github profile :3

For cases like the one _we're having right now_.

**Comment by BillytheOrc** [comment]
Noted @Levitanious  
Thank you :D

**Comment by Levitanious** [comment]
I guess it's pretty much it for now, closing :3rd_place_medal: 

Good job with everything, JL. Good job.
