### ISSUE TITLE
Difficulty balance is way off

### ISSUE THREAD

**Issue by ghost** [BillytheOrc/ProjectTempest-ISSUETRACKER#54]
### JL, the launch data and community's feedback has brought one apparent issue up:

**_The shit is unevenly difficult_.**

And here are the examples:
- [x] Level rates are increased, but amount of loot to support this fast growth is insufficient
> To keep the whole idea in one place you can actually slightly nudge things like chest pool spawn-at-a-time amounts and white drops. That will allow you to keep the droprates sane, but will provide people with sufficiently enough stuff to not to end up like Lexy and his bundle of people trying Ragefire Chasm in **_gray_** gear. (They managed it, btw)

- [x] Lowlevel quests are _hidden_, it might work in early locations but not somewhere like STV
> Here's the thing: people assume that these quests don't exist or are simply having time of their lives trying to click every other NPC out there. That doesn't do, it's a money-maker, it's a time-sinker, it's something that should be shown at all times if you make people skip a lot of content. It's the feeling of stuff around you, ffs. It matters in long-term.

- [x] Prices on skills are too darn high! Or are they?
> Now, people will bitch about it all the time, but if you will adjust coin drop rates slightly... Yes, i believe that it will help actually a long way, why not? Why not, indeed. It doesn't have to be x3. It can be x1.5 for all i know, but it can't stay x1.

We have time and we can influence these things without losing the core idea, i say we try it.
The reason why we didn't catch this one during testing is because we didn't have sufficient amount of people and opinions to actually test the whole thing, or we simply didn't ask.

Waiting on your ideas / feedback, more vision.

**Comment by Camarila** [comment]
1) Green drop rate no problem, I think?
2) Low level quests are up to people to see what and where they are, besides there's things like quest helper etc if really needed
3) It's always like this, no one will be able to afford ALL their skills while leveling unless there's actual economy going on and that requires more people.

All in all I don't see problems with any of this atm, People will always bitch about something, but it's up to them to use their head to make decisions....
