### ISSUE TITLE
Loot improvements (Outland & Dungeons)

### ISSUE THREAD

**Issue by BillytheOrc** [BillytheOrc/ProjectTempest-ISSUETRACKER#7]
Outland needs an all around loot improvement for regular mobs.

The following dungeons need a loot revamp but are functional:
Hellfire Ramparts
Blood Furnace
Shattered Halls (Heroic only)
Shadow Labyrinth
Auchenai Crypts

**Comment by Levitanious** [comment]
Will take on, after the #6

**Comment by Levitanious** [comment]
#### On it. Will check off my progress in this list:

- [ ] Hellfire Ramparts
- [ ] Blood Furnace
- [ ] Shattered Halls (Heroic only)
- [ ] Shadow Labyrinth
- [ ] Auchenai Crypts
